spring:
  profiles:
    include: security
  flyway:
    enabled: false

github:
  contribution:
    star-url: https://api.github.com/search/repositories?q=user:%s stars:>=1
    count-url: https://api.github.com/search/
